// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneDayFlat.Data;

namespace OneDayFlat.Migrations
{
    [DbContext(typeof(OneDayFlatContext))]
    partial class OneDayFlatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OneDayFlat.Models.Day", b =>
                {
                    b.Property<int>("DayID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Booked");

                    b.Property<int>("FlatID");

                    b.Property<int?>("UserID");

                    b.HasKey("DayID");

                    b.HasIndex("FlatID");

                    b.ToTable("Day");
                });

            modelBuilder.Entity("OneDayFlat.Models.Flat", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DayID");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<byte[]>("Image");

                    b.Property<string>("OwnerName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.HasKey("RoomID");

                    b.ToTable("Flat");
                });

            modelBuilder.Entity("OneDayFlat.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("OneDayFlat.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("OneDayFlat.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DayForeignKey");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("Number");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("RoleID");

                    b.HasKey("UserID");

                    b.HasIndex("DayForeignKey")
                        .IsUnique()
                        .HasFilter("[DayForeignKey] IS NOT NULL");

                    b.HasIndex("RoleID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Login = "admin@gmail.com",
                            Password = "123456",
                            RoleID = 1
                        });
                });

            modelBuilder.Entity("OneDayFlat.Models.UserFlat", b =>
                {
                    b.Property<int>("UserFlatID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FlatID");

                    b.Property<int>("UserID");

                    b.HasKey("UserFlatID");

                    b.HasIndex("FlatID");

                    b.HasIndex("UserID");

                    b.ToTable("UserFlat");
                });

            modelBuilder.Entity("OneDayFlat.Models.Day", b =>
                {
                    b.HasOne("OneDayFlat.Models.Flat", "Flat")
                        .WithMany("Days")
                        .HasForeignKey("FlatID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OneDayFlat.Models.User", b =>
                {
                    b.HasOne("OneDayFlat.Models.Day", "Day")
                        .WithOne("User")
                        .HasForeignKey("OneDayFlat.Models.User", "DayForeignKey");

                    b.HasOne("OneDayFlat.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OneDayFlat.Models.UserFlat", b =>
                {
                    b.HasOne("OneDayFlat.Models.Flat", "Flat")
                        .WithMany("UserFlat")
                        .HasForeignKey("FlatID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OneDayFlat.Models.User", "User")
                        .WithMany("UserFlat")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
